### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by MaksymTymkovych** [amosgropp/IGR#13]
Hello, thank you for your project.

I want to reproduce your results.
At the moment previous link for the FAUST dataset is broken.
I tried to download dataset http://faust.is.tue.mpg.de/ from here, but seems dataset structure is different.
Can you help how to deal with that?

**Comment by amosgropp** [comment]
you need to register to the dfaust website to download the data

**Comment by MaksymTymkovych** [comment]
Yes, I did it, but seems structure of dataset is different.
http://dfaust.is.tue.mpg.de/downloads != http://faust.is.tue.mpg.de/
Or I did something wrong?
