### ISSUE TITLE
2D experiments

### ISSUE THREAD

**Issue by argosdh** [amosgropp/IGR#3]
Hi, I'm reproducing your 2D results. I generated some 2D points in data file like "circle.npy" for testing the surface learning of 2D shapes. It seems you have made an option for 2D data. But your code is basicaly developed on 3D cases. The parameter "d_in" in setup.conf only changed the input dimension of the network. However, other related parts are still not suitable for 2D expirements. I'm trying to rewrite them. It would be very kind of you if you can upload codes about this part. Thanks a lot!

**Comment by amosgropp** [comment]
sorry for the late response i missed this message. i will upload a fixed version in the next days.

**Comment by argosdh** [comment]
Thanks for your reply. Well, actually I have already revised your code for the 2D experiments. I appreciate if you can add your version of that part. I can then ensure whether I understand your code or not by comparing my code with yours. 

Another question, is it because of the normals you used in shape learning that made person results with extra "base"? I think maybe data in D-FAUST are with bad normals at foot area. Because there were many holes at the bottom of the person model.

**Comment by amosgropp** [comment]
Great! i will add my version soon ;)
regarding D-FAUST. i assume that the extra base are indeed coming from the noisy normals of the original data.
This is more noticeable when we learn the whole dataset - because some samples are very noisy.

**Comment by mikacuy** [comment]
Hi,

Congrats on your great work!

Is there any update on the code for the 2D experiments? Particularly the visualization part would be of big help to me.

Best,
Mika

**Comment by Runsong123** [comment]
> 

I am also interested in plotting the figure, I guess that the author just uses the package 'plotly', and maybe you can refer to the [code snippets](https://github.com/yifita/iso-points/blob/6faca4a09ddf1f4cae4f5d8af054f6aecd98aa8c/DSS/misc/visualize.py#L664).
I hope it will help you.

Best wishes，
Runsong

**Comment by Runsong123** [comment]
> Hi,
> 
> Congrats on your great work!
> 
> Is there any update on the code for the 2D experiments? Particularly the visualization part would be of big help to me.
> 
> Best, Mika

I am also interested in plotting the figure, I guess that the author just uses the package 'plotly', and maybe you can refer to the code snippets.
I hope it will help you.

Best wishes，
Runsong

**Comment by Runsong123** [comment]
> Hi,
> 
> Congrats on your great work!
> 
> Is there any update on the code for the 2D experiments? Particularly the visualization part would be of big help to me.
> 
> Best, Mika

I am also interested in plotting the figure, I guess that the author just uses the package 'plotly', and maybe you can refer to the [code snippets](https://github.com/yifita/iso-points/blob/6faca4a09ddf1f4cae4f5d8af054f6aecd98aa8c/DSS/misc/visualize.py#L664).
I hope it will help you.

Best wishes，
Runsong

**Comment by amosgropp** [comment]
sorry Runsong123 i don't have code snippets for 2d exp this was long time ago. I indeed used plotly

**Comment by moyutianque** [comment]
> Hi, I'm reproducing your 2D results. I generated some 2D points in data file like "circle.npy" for testing the surface learning of 2D shapes. It seems you have made an option for 2D data. But your code is basicaly developed on 3D cases. The parameter "d_in" in setup.conf only changed the input dimension of the network. However, other related parts are still not suitable for 2D expirements. I'm trying to rewrite them. It would be very kind of you if you can upload codes about this part. Thanks a lot!

Hi, haven you reproduced the results of 2D cases shown in the paper? I met trouble reproducing the results. No matter how I tune the parameters (reduce the number of layers, change the input to nerf positional embeddings, etc.), I cannot get a stable SDF for even a manually created rectangle. The reconstructed shape cannot be as perfect as shown in the paper.
