### ISSUE TITLE
Additional discrimination terms

### ISSUE THREAD

**Issue by rustlluk** [amosgropp/IGR#7]
Hello,
I am using your work to shape complete meshes from partial input point clouds. I have been able to train the network and I get satisfying results, however I have few problems I haven't been able to solve. 

I am exploring the surroundings of the reconstructed object with robotic manipulator, so I know where is a "free space" and I would like to let the net know so it does not reconstruct a mesh in these areas. 

Do you have any idea how to add the information into the net? I guess I would need to improve the loss function with some discrimination term, however it is out of scope of my math knowledge.

Thanks

**Comment by amosgropp** [comment]
Indeed the basic formulation of igr doesn’t overcome blobs on the free space. You need to add some term which encourage minimal surface. Maybe try ideas from Lipman’s new work https://youtu.be/lmjpyIWIsZg or from Atzmon’s SALD https://arxiv.org/pdf/2006.05400.pdf
