### ISSUE TITLE
How to plot reconstructed SDF as 'recon3D.png'?

### ISSUE THREAD

**Issue by MingwuZheng** [amosgropp/IGR#8]

**Comment by MingwuZheng** [comment]
Thanks for your great work! I am wondering how to plot amazing figures like 'recon3D.png', would you please offering the code?

**Comment by MingwuZheng** [comment]
I got it.

**Comment by fbhdr** [comment]
@MingwuZheng Hi, I wonder how to plot it? Thanks!

**Comment by Runsong123** [comment]
> I got it.

Hi Mingwu,

I am wondering how to do this? could you help me?

Best,
Runsong
